POST http://localhost:8080/encode
Content-Type: application/json

{
  "url": "http://www.google.com"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}
###
POST http://localhost:8080/encode
Content-Type: application/json

{
  "url": ""
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
});
%}
###
POST http://localhost:8080/encode
Content-Type: application/json

{
  "incorrectUrlParam": "http://www.google.com"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
});
%}