POST http://localhost:8080/encode
Content-Type: application/json

{
  "url": "http://www.google.com"
}

###
GET http://localhost:8080/
Accept: application/json

###
POST http://localhost:8080/encode?url=http://www.google.com
